version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: dev-dockerfile
    command: sleep infinity
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: cake_cms
      MYSQL_USER: cmsuser
      MYSQL_PASSWORD: cmspass
    ports:
      - 8000:80
    volumes:
      - .:/workspace
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: cake_cms
      MYSQL_USER: cmsuser
      MYSQL_PASSWORD: cmspass
    image: mysql:8
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
