version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: prod-dockerfile
    ports:
      - 8000:80
    volumes:
      - ./cms:/cms
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: cms
      MYSQL_USER: cmsuser
      MYSQL_PASSWORD: cmspass
    image: mysql:8
